import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className="flex min-h-screen">
					<aside className="w-64 border-r border-zinc-200 dark:border-zinc-800 p-6 hidden md:block fixed h-full overflow-y-auto">
						<nav className="flex flex-col gap-4">
							<Link href="/" className="font-bold text-xl mb-4 block">
								Material UI
							</Link>
							<div className="flex flex-col gap-2">
								<span className="text-sm font-semibold text-zinc-500 uppercase tracking-wider">
									Components
								</span>
								<Link
									href="/docs/button"
									className="text-zinc-700 dark:text-zinc-300 hover:text-black dark:hover:text-white transition-colors"
								>
									Button
								</Link>
								<Link
									href="/docs/navigation-rail"
									className="text-zinc-700 dark:text-zinc-300 hover:text-black dark:hover:text-white transition-colors"
								>
									Navigation Rail
								</Link>
							</div>
						</nav>
					</aside>
					<main className="flex-1 p-8 max-w-4xl mx-auto md:ml-64">
						<div className="prose prose-zinc dark:prose-invert max-w-none">
							{children}
						</div>
					</main>
				</div>
			</body>
		</html>
	);
}
